{-
   Asana

   This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/developer-docs/master/defs/asana_oas.yaml).

   OpenAPI Version: 3.0.0
   Asana API version: 1.0
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : Asana.Logging
Logging functions
-}
{-# LANGUAGE CPP #-}

#ifdef USE_KATIP

module Asana.Logging
  ( module Asana.LoggingKatip
  ) where

import Asana.LoggingKatip

#else

module Asana.Logging
  ( module Asana.LoggingMonadLogger
  ) where

import Asana.LoggingMonadLogger

#endif
