{-
   Asana

   This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/developer-docs/master/defs/asana_oas.yaml).

   OpenAPI Version: 3.0.0
   Asana API version: 1.0
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : Asana.API.Portfolios
-}

{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MonoLocalBinds #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-binds -fno-warn-unused-imports #-}

module Asana.API.Portfolios where

import Asana.Core
import Asana.MimeTypes
import Asana.Model as M

import qualified Data.Aeson as A
import qualified Data.ByteString as B
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Typeable, TypeRep, typeOf, typeRep)
import qualified Data.Foldable as P
import qualified Data.Map as Map
import qualified Data.Maybe as P
import qualified Data.Proxy as P (Proxy(..))
import qualified Data.Set as Set
import qualified Data.String as P
import qualified Data.Text as T
import qualified Data.Text.Encoding as T
import qualified Data.Text.Lazy as TL
import qualified Data.Text.Lazy.Encoding as TL
import qualified Data.Time as TI
import qualified Network.HTTP.Client.MultipartFormData as NH
import qualified Network.HTTP.Media as ME
import qualified Network.HTTP.Types as NH
import qualified Web.FormUrlEncoded as WH
import qualified Web.HttpApiData as WH

import Data.Text (Text)
import GHC.Base ((<|>))

import Prelude ((==),(/=),($), (.),(<$>),(<*>),(>>=),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

-- * Operations


-- ** Portfolios

-- *** addCustomFieldSettingForPortfolio

-- | @POST \/portfolios\/{portfolio_gid}\/addCustomFieldSetting@
-- 
-- Add a custom field to a portfolio
-- 
-- Custom fields are associated with portfolios by way of custom field settings.  This method creates a setting for the portfolio.
-- 
-- AuthMethod: 'AuthOAuthOauth2', 'AuthBasicPersonalAccessToken'
-- 
addCustomFieldSettingForPortfolio 
  :: (Consumes AddCustomFieldSettingForPortfolio MimeJSON, MimeRender MimeJSON InlineObject11)
  => InlineObject11 -- ^ "inlineObject11"
  -> PortfolioGid -- ^ "portfolioGid" -  Globally unique identifier for the portfolio.
  -> AsanaRequest AddCustomFieldSettingForPortfolio MimeJSON InlineResponse2001 MimeJSON
addCustomFieldSettingForPortfolio inlineObject11 (PortfolioGid portfolioGid) =
  _mkRequest "POST" ["/portfolios/",toPath portfolioGid,"/addCustomFieldSetting"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthOAuthOauth2)
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicPersonalAccessToken)
    `setBodyParam` inlineObject11

data AddCustomFieldSettingForPortfolio 
instance HasBodyParam AddCustomFieldSettingForPortfolio InlineObject11 

-- | /Optional Param/ "opt_pretty" - Provides “pretty” output. Provides the response in a “pretty” format. In the case of JSON this means doing proper line breaking and indentation to make it readable. This will take extra time and increase the response size so it is advisable only to use this during debugging.
instance HasOptionalParam AddCustomFieldSettingForPortfolio OptPretty where
  applyOptionalParam req (OptPretty xs) =
    req `setQuery` toQuery ("opt_pretty", Just xs)

-- | @application/json@
instance Consumes AddCustomFieldSettingForPortfolio MimeJSON

-- | @application/json@
instance Produces AddCustomFieldSettingForPortfolio MimeJSON


-- *** addItemForPortfolio

-- | @POST \/portfolios\/{portfolio_gid}\/addItem@
-- 
-- Add a portfolio item
-- 
-- Add an item to a portfolio. Returns an empty data block.
-- 
-- AuthMethod: 'AuthOAuthOauth2', 'AuthBasicPersonalAccessToken'
-- 
addItemForPortfolio 
  :: (Consumes AddItemForPortfolio MimeJSON, MimeRender MimeJSON InlineObject9)
  => InlineObject9 -- ^ "inlineObject9"
  -> PortfolioGid -- ^ "portfolioGid" -  Globally unique identifier for the portfolio.
  -> AsanaRequest AddItemForPortfolio MimeJSON InlineResponse2001 MimeJSON
addItemForPortfolio inlineObject9 (PortfolioGid portfolioGid) =
  _mkRequest "POST" ["/portfolios/",toPath portfolioGid,"/addItem"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthOAuthOauth2)
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicPersonalAccessToken)
    `setBodyParam` inlineObject9

data AddItemForPortfolio 
instance HasBodyParam AddItemForPortfolio InlineObject9 

-- | /Optional Param/ "opt_pretty" - Provides “pretty” output. Provides the response in a “pretty” format. In the case of JSON this means doing proper line breaking and indentation to make it readable. This will take extra time and increase the response size so it is advisable only to use this during debugging.
instance HasOptionalParam AddItemForPortfolio OptPretty where
  applyOptionalParam req (OptPretty xs) =
    req `setQuery` toQuery ("opt_pretty", Just xs)

-- | /Optional Param/ "opt_fields" - Defines fields to return. Some requests return *compact* representations of objects in order to conserve resources and complete the request more efficiently. Other times requests return more information than you may need. This option allows you to list the exact set of fields that the API should be sure to return for the objects. The field names should be provided as paths, described below. The id of included objects will always be returned, regardless of the field options.
instance HasOptionalParam AddItemForPortfolio OptFields where
  applyOptionalParam req (OptFields xs) =
    req `setQuery` toQueryColl CommaSeparated ("opt_fields", Just xs)

-- | @application/json@
instance Consumes AddItemForPortfolio MimeJSON

-- | @application/json@
instance Produces AddItemForPortfolio MimeJSON


-- *** addMembersForPortfolio

-- | @POST \/portfolios\/{portfolio_gid}\/addMembers@
-- 
-- Add users to a portfolio
-- 
-- Adds the specified list of users as members of the portfolio. Returns the updated portfolio record.
-- 
-- AuthMethod: 'AuthOAuthOauth2', 'AuthBasicPersonalAccessToken'
-- 
addMembersForPortfolio 
  :: (Consumes AddMembersForPortfolio MimeJSON, MimeRender MimeJSON InlineObject13)
  => InlineObject13 -- ^ "inlineObject13"
  -> PortfolioGid -- ^ "portfolioGid" -  Globally unique identifier for the portfolio.
  -> AsanaRequest AddMembersForPortfolio MimeJSON InlineResponse2001 MimeJSON
addMembersForPortfolio inlineObject13 (PortfolioGid portfolioGid) =
  _mkRequest "POST" ["/portfolios/",toPath portfolioGid,"/addMembers"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthOAuthOauth2)
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicPersonalAccessToken)
    `setBodyParam` inlineObject13

data AddMembersForPortfolio 
instance HasBodyParam AddMembersForPortfolio InlineObject13 

-- | /Optional Param/ "opt_pretty" - Provides “pretty” output. Provides the response in a “pretty” format. In the case of JSON this means doing proper line breaking and indentation to make it readable. This will take extra time and increase the response size so it is advisable only to use this during debugging.
instance HasOptionalParam AddMembersForPortfolio OptPretty where
  applyOptionalParam req (OptPretty xs) =
    req `setQuery` toQuery ("opt_pretty", Just xs)

-- | /Optional Param/ "opt_fields" - Defines fields to return. Some requests return *compact* representations of objects in order to conserve resources and complete the request more efficiently. Other times requests return more information than you may need. This option allows you to list the exact set of fields that the API should be sure to return for the objects. The field names should be provided as paths, described below. The id of included objects will always be returned, regardless of the field options.
instance HasOptionalParam AddMembersForPortfolio OptFields where
  applyOptionalParam req (OptFields xs) =
    req `setQuery` toQueryColl CommaSeparated ("opt_fields", Just xs)

-- | @application/json@
instance Consumes AddMembersForPortfolio MimeJSON

-- | @application/json@
instance Produces AddMembersForPortfolio MimeJSON


-- *** createPortfolio

-- | @POST \/portfolios@
-- 
-- Create a portfolio
-- 
-- Creates a new portfolio in the given workspace with the supplied name.  Note that portfolios created in the Asana UI may have some state (like the “Priority” custom field) which is automatically added to the portfolio when it is created. Portfolios created via our API will *not* be created with the same initial state to allow integrations to create their own starting state on a portfolio.
-- 
-- AuthMethod: 'AuthOAuthOauth2', 'AuthBasicPersonalAccessToken'
-- 
createPortfolio 
  :: (Consumes CreatePortfolio MimeJSON, MimeRender MimeJSON InlineObject7)
  => InlineObject7 -- ^ "inlineObject7"
  -> AsanaRequest CreatePortfolio MimeJSON InlineResponse2013 MimeJSON
createPortfolio inlineObject7 =
  _mkRequest "POST" ["/portfolios"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthOAuthOauth2)
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicPersonalAccessToken)
    `setBodyParam` inlineObject7

data CreatePortfolio 
instance HasBodyParam CreatePortfolio InlineObject7 

-- | /Optional Param/ "opt_pretty" - Provides “pretty” output. Provides the response in a “pretty” format. In the case of JSON this means doing proper line breaking and indentation to make it readable. This will take extra time and increase the response size so it is advisable only to use this during debugging.
instance HasOptionalParam CreatePortfolio OptPretty where
  applyOptionalParam req (OptPretty xs) =
    req `setQuery` toQuery ("opt_pretty", Just xs)

-- | /Optional Param/ "opt_fields" - Defines fields to return. Some requests return *compact* representations of objects in order to conserve resources and complete the request more efficiently. Other times requests return more information than you may need. This option allows you to list the exact set of fields that the API should be sure to return for the objects. The field names should be provided as paths, described below. The id of included objects will always be returned, regardless of the field options.
instance HasOptionalParam CreatePortfolio OptFields where
  applyOptionalParam req (OptFields xs) =
    req `setQuery` toQueryColl CommaSeparated ("opt_fields", Just xs)

-- | @application/json@
instance Consumes CreatePortfolio MimeJSON

-- | @application/json@
instance Produces CreatePortfolio MimeJSON


-- *** deletePortfolio

-- | @DELETE \/portfolios\/{portfolio_gid}@
-- 
-- Delete a portfolio
-- 
-- An existing portfolio can be deleted by making a DELETE request on the URL for that portfolio.  Returns an empty data record.
-- 
-- AuthMethod: 'AuthOAuthOauth2', 'AuthBasicPersonalAccessToken'
-- 
deletePortfolio 
  :: PortfolioGid -- ^ "portfolioGid" -  Globally unique identifier for the portfolio.
  -> AsanaRequest DeletePortfolio MimeNoContent InlineResponse2001 MimeJSON
deletePortfolio (PortfolioGid portfolioGid) =
  _mkRequest "DELETE" ["/portfolios/",toPath portfolioGid]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthOAuthOauth2)
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicPersonalAccessToken)

data DeletePortfolio  

-- | /Optional Param/ "opt_pretty" - Provides “pretty” output. Provides the response in a “pretty” format. In the case of JSON this means doing proper line breaking and indentation to make it readable. This will take extra time and increase the response size so it is advisable only to use this during debugging.
instance HasOptionalParam DeletePortfolio OptPretty where
  applyOptionalParam req (OptPretty xs) =
    req `setQuery` toQuery ("opt_pretty", Just xs)

-- | /Optional Param/ "opt_fields" - Defines fields to return. Some requests return *compact* representations of objects in order to conserve resources and complete the request more efficiently. Other times requests return more information than you may need. This option allows you to list the exact set of fields that the API should be sure to return for the objects. The field names should be provided as paths, described below. The id of included objects will always be returned, regardless of the field options.
instance HasOptionalParam DeletePortfolio OptFields where
  applyOptionalParam req (OptFields xs) =
    req `setQuery` toQueryColl CommaSeparated ("opt_fields", Just xs)
-- | @application/json@
instance Produces DeletePortfolio MimeJSON


-- *** getItemsForPortfolio

-- | @GET \/portfolios\/{portfolio_gid}\/items@
-- 
-- Get portfolio items
-- 
-- Get a list of the items in compact form in a portfolio.
-- 
-- AuthMethod: 'AuthOAuthOauth2', 'AuthBasicPersonalAccessToken'
-- 
getItemsForPortfolio 
  :: PortfolioGid -- ^ "portfolioGid" -  Globally unique identifier for the portfolio.
  -> AsanaRequest GetItemsForPortfolio MimeNoContent InlineResponse20011 MimeJSON
getItemsForPortfolio (PortfolioGid portfolioGid) =
  _mkRequest "GET" ["/portfolios/",toPath portfolioGid,"/items"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthOAuthOauth2)
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicPersonalAccessToken)

data GetItemsForPortfolio  

-- | /Optional Param/ "opt_pretty" - Provides “pretty” output. Provides the response in a “pretty” format. In the case of JSON this means doing proper line breaking and indentation to make it readable. This will take extra time and increase the response size so it is advisable only to use this during debugging.
instance HasOptionalParam GetItemsForPortfolio OptPretty where
  applyOptionalParam req (OptPretty xs) =
    req `setQuery` toQuery ("opt_pretty", Just xs)

-- | /Optional Param/ "opt_fields" - Defines fields to return. Some requests return *compact* representations of objects in order to conserve resources and complete the request more efficiently. Other times requests return more information than you may need. This option allows you to list the exact set of fields that the API should be sure to return for the objects. The field names should be provided as paths, described below. The id of included objects will always be returned, regardless of the field options.
instance HasOptionalParam GetItemsForPortfolio OptFields where
  applyOptionalParam req (OptFields xs) =
    req `setQuery` toQueryColl CommaSeparated ("opt_fields", Just xs)

-- | /Optional Param/ "limit" - Results per page. The number of objects to return per page. The value must be between 1 and 100.
instance HasOptionalParam GetItemsForPortfolio Limit where
  applyOptionalParam req (Limit xs) =
    req `setQuery` toQuery ("limit", Just xs)

-- | /Optional Param/ "offset" - Offset token. An offset to the next page returned by the API. A pagination request will return an offset token, which can be used as an input parameter to the next request. If an offset is not passed in, the API will return the first page of results. 'Note: You can only pass in an offset that was returned to you via a previously paginated request.'
instance HasOptionalParam GetItemsForPortfolio Offset where
  applyOptionalParam req (Offset xs) =
    req `setQuery` toQuery ("offset", Just xs)
-- | @application/json@
instance Produces GetItemsForPortfolio MimeJSON


-- *** getPortfolio

-- | @GET \/portfolios\/{portfolio_gid}@
-- 
-- Get a portfolio
-- 
-- Returns the complete portfolio record for a single portfolio.
-- 
-- AuthMethod: 'AuthOAuthOauth2', 'AuthBasicPersonalAccessToken'
-- 
getPortfolio 
  :: PortfolioGid -- ^ "portfolioGid" -  Globally unique identifier for the portfolio.
  -> AsanaRequest GetPortfolio MimeNoContent InlineResponse2013 MimeJSON
getPortfolio (PortfolioGid portfolioGid) =
  _mkRequest "GET" ["/portfolios/",toPath portfolioGid]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthOAuthOauth2)
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicPersonalAccessToken)

data GetPortfolio  

-- | /Optional Param/ "opt_pretty" - Provides “pretty” output. Provides the response in a “pretty” format. In the case of JSON this means doing proper line breaking and indentation to make it readable. This will take extra time and increase the response size so it is advisable only to use this during debugging.
instance HasOptionalParam GetPortfolio OptPretty where
  applyOptionalParam req (OptPretty xs) =
    req `setQuery` toQuery ("opt_pretty", Just xs)

-- | /Optional Param/ "opt_fields" - Defines fields to return. Some requests return *compact* representations of objects in order to conserve resources and complete the request more efficiently. Other times requests return more information than you may need. This option allows you to list the exact set of fields that the API should be sure to return for the objects. The field names should be provided as paths, described below. The id of included objects will always be returned, regardless of the field options.
instance HasOptionalParam GetPortfolio OptFields where
  applyOptionalParam req (OptFields xs) =
    req `setQuery` toQueryColl CommaSeparated ("opt_fields", Just xs)
-- | @application/json@
instance Produces GetPortfolio MimeJSON


-- *** getPortfolios

-- | @GET \/portfolios@
-- 
-- Get multiple portfolios
-- 
-- Returns a list of the portfolios in compact representation that are owned by the current API user.
-- 
-- AuthMethod: 'AuthOAuthOauth2', 'AuthBasicPersonalAccessToken'
-- 
getPortfolios 
  :: Workspace -- ^ "workspace" -  The workspace or organization to filter portfolios on.
  -> Owner -- ^ "owner" -  The user who owns the portfolio. Currently, API users can only get a list of portfolios that they themselves own.
  -> AsanaRequest GetPortfolios MimeNoContent InlineResponse20010 MimeJSON
getPortfolios (Workspace workspace) (Owner owner) =
  _mkRequest "GET" ["/portfolios"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthOAuthOauth2)
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicPersonalAccessToken)
    `setQuery` toQuery ("workspace", Just workspace)
    `setQuery` toQuery ("owner", Just owner)

data GetPortfolios  

-- | /Optional Param/ "opt_pretty" - Provides “pretty” output. Provides the response in a “pretty” format. In the case of JSON this means doing proper line breaking and indentation to make it readable. This will take extra time and increase the response size so it is advisable only to use this during debugging.
instance HasOptionalParam GetPortfolios OptPretty where
  applyOptionalParam req (OptPretty xs) =
    req `setQuery` toQuery ("opt_pretty", Just xs)

-- | /Optional Param/ "opt_fields" - Defines fields to return. Some requests return *compact* representations of objects in order to conserve resources and complete the request more efficiently. Other times requests return more information than you may need. This option allows you to list the exact set of fields that the API should be sure to return for the objects. The field names should be provided as paths, described below. The id of included objects will always be returned, regardless of the field options.
instance HasOptionalParam GetPortfolios OptFields where
  applyOptionalParam req (OptFields xs) =
    req `setQuery` toQueryColl CommaSeparated ("opt_fields", Just xs)

-- | /Optional Param/ "limit" - Results per page. The number of objects to return per page. The value must be between 1 and 100.
instance HasOptionalParam GetPortfolios Limit where
  applyOptionalParam req (Limit xs) =
    req `setQuery` toQuery ("limit", Just xs)

-- | /Optional Param/ "offset" - Offset token. An offset to the next page returned by the API. A pagination request will return an offset token, which can be used as an input parameter to the next request. If an offset is not passed in, the API will return the first page of results. 'Note: You can only pass in an offset that was returned to you via a previously paginated request.'
instance HasOptionalParam GetPortfolios Offset where
  applyOptionalParam req (Offset xs) =
    req `setQuery` toQuery ("offset", Just xs)
-- | @application/json@
instance Produces GetPortfolios MimeJSON


-- *** removeCustomFieldSettingForPortfolio

-- | @POST \/portfolios\/{portfolio_gid}\/removeCustomFieldSetting@
-- 
-- Remove a custom field from a portfolio
-- 
-- Removes a custom field setting from a portfolio.
-- 
-- AuthMethod: 'AuthOAuthOauth2', 'AuthBasicPersonalAccessToken'
-- 
removeCustomFieldSettingForPortfolio 
  :: (Consumes RemoveCustomFieldSettingForPortfolio MimeJSON, MimeRender MimeJSON InlineObject12)
  => InlineObject12 -- ^ "inlineObject12"
  -> PortfolioGid -- ^ "portfolioGid" -  Globally unique identifier for the portfolio.
  -> AsanaRequest RemoveCustomFieldSettingForPortfolio MimeJSON InlineResponse2001 MimeJSON
removeCustomFieldSettingForPortfolio inlineObject12 (PortfolioGid portfolioGid) =
  _mkRequest "POST" ["/portfolios/",toPath portfolioGid,"/removeCustomFieldSetting"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthOAuthOauth2)
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicPersonalAccessToken)
    `setBodyParam` inlineObject12

data RemoveCustomFieldSettingForPortfolio 
instance HasBodyParam RemoveCustomFieldSettingForPortfolio InlineObject12 

-- | /Optional Param/ "opt_pretty" - Provides “pretty” output. Provides the response in a “pretty” format. In the case of JSON this means doing proper line breaking and indentation to make it readable. This will take extra time and increase the response size so it is advisable only to use this during debugging.
instance HasOptionalParam RemoveCustomFieldSettingForPortfolio OptPretty where
  applyOptionalParam req (OptPretty xs) =
    req `setQuery` toQuery ("opt_pretty", Just xs)

-- | @application/json@
instance Consumes RemoveCustomFieldSettingForPortfolio MimeJSON

-- | @application/json@
instance Produces RemoveCustomFieldSettingForPortfolio MimeJSON


-- *** removeItemForPortfolio

-- | @POST \/portfolios\/{portfolio_gid}\/removeItem@
-- 
-- Remove a portfolio item
-- 
-- Remove an item from a portfolio. Returns an empty data block.
-- 
-- AuthMethod: 'AuthOAuthOauth2', 'AuthBasicPersonalAccessToken'
-- 
removeItemForPortfolio 
  :: (Consumes RemoveItemForPortfolio MimeJSON, MimeRender MimeJSON InlineObject10)
  => InlineObject10 -- ^ "inlineObject10"
  -> PortfolioGid -- ^ "portfolioGid" -  Globally unique identifier for the portfolio.
  -> AsanaRequest RemoveItemForPortfolio MimeJSON InlineResponse2001 MimeJSON
removeItemForPortfolio inlineObject10 (PortfolioGid portfolioGid) =
  _mkRequest "POST" ["/portfolios/",toPath portfolioGid,"/removeItem"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthOAuthOauth2)
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicPersonalAccessToken)
    `setBodyParam` inlineObject10

data RemoveItemForPortfolio 
instance HasBodyParam RemoveItemForPortfolio InlineObject10 

-- | /Optional Param/ "opt_pretty" - Provides “pretty” output. Provides the response in a “pretty” format. In the case of JSON this means doing proper line breaking and indentation to make it readable. This will take extra time and increase the response size so it is advisable only to use this during debugging.
instance HasOptionalParam RemoveItemForPortfolio OptPretty where
  applyOptionalParam req (OptPretty xs) =
    req `setQuery` toQuery ("opt_pretty", Just xs)

-- | /Optional Param/ "opt_fields" - Defines fields to return. Some requests return *compact* representations of objects in order to conserve resources and complete the request more efficiently. Other times requests return more information than you may need. This option allows you to list the exact set of fields that the API should be sure to return for the objects. The field names should be provided as paths, described below. The id of included objects will always be returned, regardless of the field options.
instance HasOptionalParam RemoveItemForPortfolio OptFields where
  applyOptionalParam req (OptFields xs) =
    req `setQuery` toQueryColl CommaSeparated ("opt_fields", Just xs)

-- | @application/json@
instance Consumes RemoveItemForPortfolio MimeJSON

-- | @application/json@
instance Produces RemoveItemForPortfolio MimeJSON


-- *** removeMembersForPortfolio

-- | @POST \/portfolios\/{portfolio_gid}\/removeMembers@
-- 
-- Remove users from a portfolio
-- 
-- Removes the specified list of users from members of the portfolio. Returns the updated portfolio record.
-- 
-- AuthMethod: 'AuthOAuthOauth2', 'AuthBasicPersonalAccessToken'
-- 
removeMembersForPortfolio 
  :: (Consumes RemoveMembersForPortfolio MimeJSON, MimeRender MimeJSON InlineObject14)
  => InlineObject14 -- ^ "inlineObject14"
  -> PortfolioGid -- ^ "portfolioGid" -  Globally unique identifier for the portfolio.
  -> AsanaRequest RemoveMembersForPortfolio MimeJSON InlineResponse2001 MimeJSON
removeMembersForPortfolio inlineObject14 (PortfolioGid portfolioGid) =
  _mkRequest "POST" ["/portfolios/",toPath portfolioGid,"/removeMembers"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthOAuthOauth2)
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicPersonalAccessToken)
    `setBodyParam` inlineObject14

data RemoveMembersForPortfolio 
instance HasBodyParam RemoveMembersForPortfolio InlineObject14 

-- | /Optional Param/ "opt_pretty" - Provides “pretty” output. Provides the response in a “pretty” format. In the case of JSON this means doing proper line breaking and indentation to make it readable. This will take extra time and increase the response size so it is advisable only to use this during debugging.
instance HasOptionalParam RemoveMembersForPortfolio OptPretty where
  applyOptionalParam req (OptPretty xs) =
    req `setQuery` toQuery ("opt_pretty", Just xs)

-- | /Optional Param/ "opt_fields" - Defines fields to return. Some requests return *compact* representations of objects in order to conserve resources and complete the request more efficiently. Other times requests return more information than you may need. This option allows you to list the exact set of fields that the API should be sure to return for the objects. The field names should be provided as paths, described below. The id of included objects will always be returned, regardless of the field options.
instance HasOptionalParam RemoveMembersForPortfolio OptFields where
  applyOptionalParam req (OptFields xs) =
    req `setQuery` toQueryColl CommaSeparated ("opt_fields", Just xs)

-- | @application/json@
instance Consumes RemoveMembersForPortfolio MimeJSON

-- | @application/json@
instance Produces RemoveMembersForPortfolio MimeJSON


-- *** updatePortfolio

-- | @PUT \/portfolios\/{portfolio_gid}@
-- 
-- Update a portfolio
-- 
-- An existing portfolio can be updated by making a PUT request on the URL for that portfolio. Only the fields provided in the `data` block will be updated; any unspecified fields will remain unchanged.  Returns the complete updated portfolio record.
-- 
-- AuthMethod: 'AuthOAuthOauth2', 'AuthBasicPersonalAccessToken'
-- 
updatePortfolio 
  :: (Consumes UpdatePortfolio MimeJSON, MimeRender MimeJSON InlineObject8)
  => InlineObject8 -- ^ "inlineObject8"
  -> PortfolioGid -- ^ "portfolioGid" -  Globally unique identifier for the portfolio.
  -> AsanaRequest UpdatePortfolio MimeJSON InlineResponse2013 MimeJSON
updatePortfolio inlineObject8 (PortfolioGid portfolioGid) =
  _mkRequest "PUT" ["/portfolios/",toPath portfolioGid]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthOAuthOauth2)
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicPersonalAccessToken)
    `setBodyParam` inlineObject8

data UpdatePortfolio 
instance HasBodyParam UpdatePortfolio InlineObject8 

-- | /Optional Param/ "opt_pretty" - Provides “pretty” output. Provides the response in a “pretty” format. In the case of JSON this means doing proper line breaking and indentation to make it readable. This will take extra time and increase the response size so it is advisable only to use this during debugging.
instance HasOptionalParam UpdatePortfolio OptPretty where
  applyOptionalParam req (OptPretty xs) =
    req `setQuery` toQuery ("opt_pretty", Just xs)

-- | /Optional Param/ "opt_fields" - Defines fields to return. Some requests return *compact* representations of objects in order to conserve resources and complete the request more efficiently. Other times requests return more information than you may need. This option allows you to list the exact set of fields that the API should be sure to return for the objects. The field names should be provided as paths, described below. The id of included objects will always be returned, regardless of the field options.
instance HasOptionalParam UpdatePortfolio OptFields where
  applyOptionalParam req (OptFields xs) =
    req `setQuery` toQueryColl CommaSeparated ("opt_fields", Just xs)

-- | @application/json@
instance Consumes UpdatePortfolio MimeJSON

-- | @application/json@
instance Produces UpdatePortfolio MimeJSON

