{-
   Asana

   This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/developer-docs/master/defs/asana_oas.yaml).

   OpenAPI Version: 3.0.0
   Asana API version: 1.0
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : Asana.API.PortfolioMemberships
-}

{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MonoLocalBinds #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-binds -fno-warn-unused-imports #-}

module Asana.API.PortfolioMemberships where

import Asana.Core
import Asana.MimeTypes
import Asana.Model as M

import qualified Data.Aeson as A
import qualified Data.ByteString as B
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Typeable, TypeRep, typeOf, typeRep)
import qualified Data.Foldable as P
import qualified Data.Map as Map
import qualified Data.Maybe as P
import qualified Data.Proxy as P (Proxy(..))
import qualified Data.Set as Set
import qualified Data.String as P
import qualified Data.Text as T
import qualified Data.Text.Encoding as T
import qualified Data.Text.Lazy as TL
import qualified Data.Text.Lazy.Encoding as TL
import qualified Data.Time as TI
import qualified Network.HTTP.Client.MultipartFormData as NH
import qualified Network.HTTP.Media as ME
import qualified Network.HTTP.Types as NH
import qualified Web.FormUrlEncoded as WH
import qualified Web.HttpApiData as WH

import Data.Text (Text)
import GHC.Base ((<|>))

import Prelude ((==),(/=),($), (.),(<$>),(<*>),(>>=),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

-- * Operations


-- ** PortfolioMemberships

-- *** getPortfolioMembership

-- | @GET \/portfolio_memberships\/{portfolio_membership_gid}@
-- 
-- Get a portfolio membership
-- 
-- Returns the complete portfolio record for a single portfolio membership.
-- 
-- AuthMethod: 'AuthOAuthOauth2', 'AuthBasicPersonalAccessToken'
-- 
getPortfolioMembership 
  :: PortfolioMembershipGid -- ^ "portfolioMembershipGid"
  -> AsanaRequest GetPortfolioMembership MimeNoContent InlineResponse2009 MimeJSON
getPortfolioMembership (PortfolioMembershipGid portfolioMembershipGid) =
  _mkRequest "GET" ["/portfolio_memberships/",toPath portfolioMembershipGid]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthOAuthOauth2)
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicPersonalAccessToken)

data GetPortfolioMembership  

-- | /Optional Param/ "opt_pretty" - Provides “pretty” output. Provides the response in a “pretty” format. In the case of JSON this means doing proper line breaking and indentation to make it readable. This will take extra time and increase the response size so it is advisable only to use this during debugging.
instance HasOptionalParam GetPortfolioMembership OptPretty where
  applyOptionalParam req (OptPretty xs) =
    req `setQuery` toQuery ("opt_pretty", Just xs)

-- | /Optional Param/ "opt_fields" - Defines fields to return. Some requests return *compact* representations of objects in order to conserve resources and complete the request more efficiently. Other times requests return more information than you may need. This option allows you to list the exact set of fields that the API should be sure to return for the objects. The field names should be provided as paths, described below. The id of included objects will always be returned, regardless of the field options.
instance HasOptionalParam GetPortfolioMembership OptFields where
  applyOptionalParam req (OptFields xs) =
    req `setQuery` toQueryColl CommaSeparated ("opt_fields", Just xs)
-- | @application/json@
instance Produces GetPortfolioMembership MimeJSON


-- *** getPortfolioMemberships

-- | @GET \/portfolio_memberships@
-- 
-- Get multiple portfolio memberships
-- 
-- Returns a list of portfolio memberships in compact representation. You must specify `portfolio`, `portfolio` and `user`, or `workspace` and `user`.
-- 
-- AuthMethod: 'AuthOAuthOauth2', 'AuthBasicPersonalAccessToken'
-- 
getPortfolioMemberships 
  :: AsanaRequest GetPortfolioMemberships MimeNoContent InlineResponse2008 MimeJSON
getPortfolioMemberships =
  _mkRequest "GET" ["/portfolio_memberships"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthOAuthOauth2)
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicPersonalAccessToken)

data GetPortfolioMemberships  

-- | /Optional Param/ "portfolio" - The portfolio to filter results on.
instance HasOptionalParam GetPortfolioMemberships Portfolio where
  applyOptionalParam req (Portfolio xs) =
    req `setQuery` toQuery ("portfolio", Just xs)

-- | /Optional Param/ "workspace" - The workspace to filter results on.
instance HasOptionalParam GetPortfolioMemberships Workspace where
  applyOptionalParam req (Workspace xs) =
    req `setQuery` toQuery ("workspace", Just xs)

-- | /Optional Param/ "user" - A string identifying a user. This can either be the string \"me\", an email, or the gid of a user.
instance HasOptionalParam GetPortfolioMemberships User where
  applyOptionalParam req (User xs) =
    req `setQuery` toQuery ("user", Just xs)

-- | /Optional Param/ "opt_pretty" - Provides “pretty” output. Provides the response in a “pretty” format. In the case of JSON this means doing proper line breaking and indentation to make it readable. This will take extra time and increase the response size so it is advisable only to use this during debugging.
instance HasOptionalParam GetPortfolioMemberships OptPretty where
  applyOptionalParam req (OptPretty xs) =
    req `setQuery` toQuery ("opt_pretty", Just xs)

-- | /Optional Param/ "opt_fields" - Defines fields to return. Some requests return *compact* representations of objects in order to conserve resources and complete the request more efficiently. Other times requests return more information than you may need. This option allows you to list the exact set of fields that the API should be sure to return for the objects. The field names should be provided as paths, described below. The id of included objects will always be returned, regardless of the field options.
instance HasOptionalParam GetPortfolioMemberships OptFields where
  applyOptionalParam req (OptFields xs) =
    req `setQuery` toQueryColl CommaSeparated ("opt_fields", Just xs)

-- | /Optional Param/ "limit" - Results per page. The number of objects to return per page. The value must be between 1 and 100.
instance HasOptionalParam GetPortfolioMemberships Limit where
  applyOptionalParam req (Limit xs) =
    req `setQuery` toQuery ("limit", Just xs)

-- | /Optional Param/ "offset" - Offset token. An offset to the next page returned by the API. A pagination request will return an offset token, which can be used as an input parameter to the next request. If an offset is not passed in, the API will return the first page of results. 'Note: You can only pass in an offset that was returned to you via a previously paginated request.'
instance HasOptionalParam GetPortfolioMemberships Offset where
  applyOptionalParam req (Offset xs) =
    req `setQuery` toQuery ("offset", Just xs)
-- | @application/json@
instance Produces GetPortfolioMemberships MimeJSON


-- *** getPortfolioMembershipsForPortfolio

-- | @GET \/portfolios\/{portfolio_gid}\/portfolio_memberships@
-- 
-- Get memberships from a portfolio
-- 
-- Returns the compact portfolio membership records for the portfolio.
-- 
-- AuthMethod: 'AuthOAuthOauth2', 'AuthBasicPersonalAccessToken'
-- 
getPortfolioMembershipsForPortfolio 
  :: PortfolioGid -- ^ "portfolioGid" -  Globally unique identifier for the portfolio.
  -> AsanaRequest GetPortfolioMembershipsForPortfolio MimeNoContent InlineResponse2008 MimeJSON
getPortfolioMembershipsForPortfolio (PortfolioGid portfolioGid) =
  _mkRequest "GET" ["/portfolios/",toPath portfolioGid,"/portfolio_memberships"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthOAuthOauth2)
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicPersonalAccessToken)

data GetPortfolioMembershipsForPortfolio  

-- | /Optional Param/ "user" - A string identifying a user. This can either be the string \"me\", an email, or the gid of a user.
instance HasOptionalParam GetPortfolioMembershipsForPortfolio User where
  applyOptionalParam req (User xs) =
    req `setQuery` toQuery ("user", Just xs)

-- | /Optional Param/ "opt_pretty" - Provides “pretty” output. Provides the response in a “pretty” format. In the case of JSON this means doing proper line breaking and indentation to make it readable. This will take extra time and increase the response size so it is advisable only to use this during debugging.
instance HasOptionalParam GetPortfolioMembershipsForPortfolio OptPretty where
  applyOptionalParam req (OptPretty xs) =
    req `setQuery` toQuery ("opt_pretty", Just xs)

-- | /Optional Param/ "opt_fields" - Defines fields to return. Some requests return *compact* representations of objects in order to conserve resources and complete the request more efficiently. Other times requests return more information than you may need. This option allows you to list the exact set of fields that the API should be sure to return for the objects. The field names should be provided as paths, described below. The id of included objects will always be returned, regardless of the field options.
instance HasOptionalParam GetPortfolioMembershipsForPortfolio OptFields where
  applyOptionalParam req (OptFields xs) =
    req `setQuery` toQueryColl CommaSeparated ("opt_fields", Just xs)

-- | /Optional Param/ "limit" - Results per page. The number of objects to return per page. The value must be between 1 and 100.
instance HasOptionalParam GetPortfolioMembershipsForPortfolio Limit where
  applyOptionalParam req (Limit xs) =
    req `setQuery` toQuery ("limit", Just xs)

-- | /Optional Param/ "offset" - Offset token. An offset to the next page returned by the API. A pagination request will return an offset token, which can be used as an input parameter to the next request. If an offset is not passed in, the API will return the first page of results. 'Note: You can only pass in an offset that was returned to you via a previously paginated request.'
instance HasOptionalParam GetPortfolioMembershipsForPortfolio Offset where
  applyOptionalParam req (Offset xs) =
    req `setQuery` toQuery ("offset", Just xs)
-- | @application/json@
instance Produces GetPortfolioMembershipsForPortfolio MimeJSON

