{-
   Asana

   This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/developer-docs/master/defs/asana_oas.yaml).

   OpenAPI Version: 3.0.0
   Asana API version: 1.0
   Generated by OpenAPI Generator (https://openapi-generator.tech)
-}

{-|
Module : Asana.API.Projects
-}

{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MonoLocalBinds #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing -fno-warn-unused-binds -fno-warn-unused-imports #-}

module Asana.API.Projects where

import Asana.Core
import Asana.MimeTypes
import Asana.Model as M

import qualified Data.Aeson as A
import qualified Data.ByteString as B
import qualified Data.ByteString.Lazy as BL
import qualified Data.Data as P (Typeable, TypeRep, typeOf, typeRep)
import qualified Data.Foldable as P
import qualified Data.Map as Map
import qualified Data.Maybe as P
import qualified Data.Proxy as P (Proxy(..))
import qualified Data.Set as Set
import qualified Data.String as P
import qualified Data.Text as T
import qualified Data.Text.Encoding as T
import qualified Data.Text.Lazy as TL
import qualified Data.Text.Lazy.Encoding as TL
import qualified Data.Time as TI
import qualified Network.HTTP.Client.MultipartFormData as NH
import qualified Network.HTTP.Media as ME
import qualified Network.HTTP.Types as NH
import qualified Web.FormUrlEncoded as WH
import qualified Web.HttpApiData as WH

import Data.Text (Text)
import GHC.Base ((<|>))

import Prelude ((==),(/=),($), (.),(<$>),(<*>),(>>=),Maybe(..),Bool(..),Char,Double,FilePath,Float,Int,Integer,String,fmap,undefined,mempty,maybe,pure,Monad,Applicative,Functor)
import qualified Prelude as P

-- * Operations


-- ** Projects

-- *** addCustomFieldSettingForProject

-- | @POST \/projects\/{project_gid}\/addCustomFieldSetting@
-- 
-- Add a custom field to a project
-- 
-- Custom fields are associated with projects by way of custom field settings.  This method creates a setting for the project.
-- 
-- AuthMethod: 'AuthOAuthOauth2', 'AuthBasicPersonalAccessToken'
-- 
addCustomFieldSettingForProject 
  :: (Consumes AddCustomFieldSettingForProject MimeJSON, MimeRender MimeJSON InlineObject21)
  => InlineObject21 -- ^ "inlineObject21"
  -> ProjectGid -- ^ "projectGid" -  Globally unique identifier for the project.
  -> AsanaRequest AddCustomFieldSettingForProject MimeJSON InlineResponse2001 MimeJSON
addCustomFieldSettingForProject inlineObject21 (ProjectGid projectGid) =
  _mkRequest "POST" ["/projects/",toPath projectGid,"/addCustomFieldSetting"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthOAuthOauth2)
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicPersonalAccessToken)
    `setBodyParam` inlineObject21

data AddCustomFieldSettingForProject 
instance HasBodyParam AddCustomFieldSettingForProject InlineObject21 

-- | /Optional Param/ "opt_pretty" - Provides “pretty” output. Provides the response in a “pretty” format. In the case of JSON this means doing proper line breaking and indentation to make it readable. This will take extra time and increase the response size so it is advisable only to use this during debugging.
instance HasOptionalParam AddCustomFieldSettingForProject OptPretty where
  applyOptionalParam req (OptPretty xs) =
    req `setQuery` toQuery ("opt_pretty", Just xs)

-- | @application/json@
instance Consumes AddCustomFieldSettingForProject MimeJSON

-- | @application/json@
instance Produces AddCustomFieldSettingForProject MimeJSON


-- *** addFollowersForProject

-- | @POST \/projects\/{project_gid}\/addFollowers@
-- 
-- Add followers to a project
-- 
-- Adds the specified list of users as followers to the project. Followers are a subset of members, therefore if the users are not already members of the project they will also become members as a result of this operation. Returns the updated project record.
-- 
-- AuthMethod: 'AuthOAuthOauth2', 'AuthBasicPersonalAccessToken'
-- 
addFollowersForProject 
  :: (Consumes AddFollowersForProject MimeJSON, MimeRender MimeJSON InlineObject25)
  => InlineObject25 -- ^ "inlineObject25"
  -> ProjectGid -- ^ "projectGid" -  Globally unique identifier for the project.
  -> AsanaRequest AddFollowersForProject MimeJSON InlineResponse2001 MimeJSON
addFollowersForProject inlineObject25 (ProjectGid projectGid) =
  _mkRequest "POST" ["/projects/",toPath projectGid,"/addFollowers"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthOAuthOauth2)
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicPersonalAccessToken)
    `setBodyParam` inlineObject25

data AddFollowersForProject 
instance HasBodyParam AddFollowersForProject InlineObject25 

-- | /Optional Param/ "opt_pretty" - Provides “pretty” output. Provides the response in a “pretty” format. In the case of JSON this means doing proper line breaking and indentation to make it readable. This will take extra time and increase the response size so it is advisable only to use this during debugging.
instance HasOptionalParam AddFollowersForProject OptPretty where
  applyOptionalParam req (OptPretty xs) =
    req `setQuery` toQuery ("opt_pretty", Just xs)

-- | /Optional Param/ "opt_fields" - Defines fields to return. Some requests return *compact* representations of objects in order to conserve resources and complete the request more efficiently. Other times requests return more information than you may need. This option allows you to list the exact set of fields that the API should be sure to return for the objects. The field names should be provided as paths, described below. The id of included objects will always be returned, regardless of the field options.
instance HasOptionalParam AddFollowersForProject OptFields where
  applyOptionalParam req (OptFields xs) =
    req `setQuery` toQueryColl CommaSeparated ("opt_fields", Just xs)

-- | @application/json@
instance Consumes AddFollowersForProject MimeJSON

-- | @application/json@
instance Produces AddFollowersForProject MimeJSON


-- *** addMembersForProject

-- | @POST \/projects\/{project_gid}\/addMembers@
-- 
-- Add users to a project
-- 
-- Adds the specified list of users as members of the project. Returns the updated project record.
-- 
-- AuthMethod: 'AuthOAuthOauth2', 'AuthBasicPersonalAccessToken'
-- 
addMembersForProject 
  :: (Consumes AddMembersForProject MimeJSON, MimeRender MimeJSON InlineObject23)
  => InlineObject23 -- ^ "inlineObject23"
  -> ProjectGid -- ^ "projectGid" -  Globally unique identifier for the project.
  -> AsanaRequest AddMembersForProject MimeJSON InlineResponse2001 MimeJSON
addMembersForProject inlineObject23 (ProjectGid projectGid) =
  _mkRequest "POST" ["/projects/",toPath projectGid,"/addMembers"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthOAuthOauth2)
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicPersonalAccessToken)
    `setBodyParam` inlineObject23

data AddMembersForProject 
instance HasBodyParam AddMembersForProject InlineObject23 

-- | /Optional Param/ "opt_pretty" - Provides “pretty” output. Provides the response in a “pretty” format. In the case of JSON this means doing proper line breaking and indentation to make it readable. This will take extra time and increase the response size so it is advisable only to use this during debugging.
instance HasOptionalParam AddMembersForProject OptPretty where
  applyOptionalParam req (OptPretty xs) =
    req `setQuery` toQuery ("opt_pretty", Just xs)

-- | /Optional Param/ "opt_fields" - Defines fields to return. Some requests return *compact* representations of objects in order to conserve resources and complete the request more efficiently. Other times requests return more information than you may need. This option allows you to list the exact set of fields that the API should be sure to return for the objects. The field names should be provided as paths, described below. The id of included objects will always be returned, regardless of the field options.
instance HasOptionalParam AddMembersForProject OptFields where
  applyOptionalParam req (OptFields xs) =
    req `setQuery` toQueryColl CommaSeparated ("opt_fields", Just xs)

-- | @application/json@
instance Consumes AddMembersForProject MimeJSON

-- | @application/json@
instance Produces AddMembersForProject MimeJSON


-- *** createProject

-- | @POST \/projects@
-- 
-- Create a project
-- 
-- Create a new project in a workspace or team.  Every project is required to be created in a specific workspace or organization, and this cannot be changed once set. Note that you can use the `workspace` parameter regardless of whether or not it is an organization.  If the workspace for your project is an organization, you must also supply a `team` to share the project with.  Returns the full record of the newly created project.
-- 
-- AuthMethod: 'AuthOAuthOauth2', 'AuthBasicPersonalAccessToken'
-- 
createProject 
  :: (Consumes CreateProject MimeJSON, MimeRender MimeJSON InlineObject16)
  => InlineObject16 -- ^ "inlineObject16"
  -> AsanaRequest CreateProject MimeJSON InlineResponse2014 MimeJSON
createProject inlineObject16 =
  _mkRequest "POST" ["/projects"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthOAuthOauth2)
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicPersonalAccessToken)
    `setBodyParam` inlineObject16

data CreateProject 
instance HasBodyParam CreateProject InlineObject16 

-- | /Optional Param/ "opt_pretty" - Provides “pretty” output. Provides the response in a “pretty” format. In the case of JSON this means doing proper line breaking and indentation to make it readable. This will take extra time and increase the response size so it is advisable only to use this during debugging.
instance HasOptionalParam CreateProject OptPretty where
  applyOptionalParam req (OptPretty xs) =
    req `setQuery` toQuery ("opt_pretty", Just xs)

-- | /Optional Param/ "opt_fields" - Defines fields to return. Some requests return *compact* representations of objects in order to conserve resources and complete the request more efficiently. Other times requests return more information than you may need. This option allows you to list the exact set of fields that the API should be sure to return for the objects. The field names should be provided as paths, described below. The id of included objects will always be returned, regardless of the field options.
instance HasOptionalParam CreateProject OptFields where
  applyOptionalParam req (OptFields xs) =
    req `setQuery` toQueryColl CommaSeparated ("opt_fields", Just xs)

-- | @application/json@
instance Consumes CreateProject MimeJSON

-- | @application/json@
instance Produces CreateProject MimeJSON


-- *** createProjectForTeam

-- | @POST \/teams\/{team_gid}\/projects@
-- 
-- Create a project in a team
-- 
-- Creates a project shared with the given team.  Returns the full record of the newly created project.
-- 
-- AuthMethod: 'AuthOAuthOauth2', 'AuthBasicPersonalAccessToken'
-- 
createProjectForTeam 
  :: (Consumes CreateProjectForTeam MimeJSON, MimeRender MimeJSON InlineObject19)
  => InlineObject19 -- ^ "inlineObject19"
  -> TeamGid -- ^ "teamGid" -  Globally unique identifier for the team.
  -> AsanaRequest CreateProjectForTeam MimeJSON InlineResponse2014 MimeJSON
createProjectForTeam inlineObject19 (TeamGid teamGid) =
  _mkRequest "POST" ["/teams/",toPath teamGid,"/projects"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthOAuthOauth2)
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicPersonalAccessToken)
    `setBodyParam` inlineObject19

data CreateProjectForTeam 
instance HasBodyParam CreateProjectForTeam InlineObject19 

-- | /Optional Param/ "opt_pretty" - Provides “pretty” output. Provides the response in a “pretty” format. In the case of JSON this means doing proper line breaking and indentation to make it readable. This will take extra time and increase the response size so it is advisable only to use this during debugging.
instance HasOptionalParam CreateProjectForTeam OptPretty where
  applyOptionalParam req (OptPretty xs) =
    req `setQuery` toQuery ("opt_pretty", Just xs)

-- | /Optional Param/ "opt_fields" - Defines fields to return. Some requests return *compact* representations of objects in order to conserve resources and complete the request more efficiently. Other times requests return more information than you may need. This option allows you to list the exact set of fields that the API should be sure to return for the objects. The field names should be provided as paths, described below. The id of included objects will always be returned, regardless of the field options.
instance HasOptionalParam CreateProjectForTeam OptFields where
  applyOptionalParam req (OptFields xs) =
    req `setQuery` toQueryColl CommaSeparated ("opt_fields", Just xs)

-- | @application/json@
instance Consumes CreateProjectForTeam MimeJSON

-- | @application/json@
instance Produces CreateProjectForTeam MimeJSON


-- *** createProjectForWorkspace

-- | @POST \/workspaces\/{workspace_gid}\/projects@
-- 
-- Create a project in a workspace
-- 
-- Returns the compact project records for all projects in the workspace.  If the workspace for your project is an organization, you must also supply a team to share the project with.  Returns the full record of the newly created project.
-- 
-- AuthMethod: 'AuthOAuthOauth2', 'AuthBasicPersonalAccessToken'
-- 
createProjectForWorkspace 
  :: (Consumes CreateProjectForWorkspace MimeJSON, MimeRender MimeJSON InlineObject20)
  => InlineObject20 -- ^ "inlineObject20"
  -> WorkspaceGid -- ^ "workspaceGid" -  Globally unique identifier for the workspace or organization.
  -> AsanaRequest CreateProjectForWorkspace MimeJSON InlineResponse2014 MimeJSON
createProjectForWorkspace inlineObject20 (WorkspaceGid workspaceGid) =
  _mkRequest "POST" ["/workspaces/",toPath workspaceGid,"/projects"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthOAuthOauth2)
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicPersonalAccessToken)
    `setBodyParam` inlineObject20

data CreateProjectForWorkspace 
instance HasBodyParam CreateProjectForWorkspace InlineObject20 

-- | /Optional Param/ "opt_pretty" - Provides “pretty” output. Provides the response in a “pretty” format. In the case of JSON this means doing proper line breaking and indentation to make it readable. This will take extra time and increase the response size so it is advisable only to use this during debugging.
instance HasOptionalParam CreateProjectForWorkspace OptPretty where
  applyOptionalParam req (OptPretty xs) =
    req `setQuery` toQuery ("opt_pretty", Just xs)

-- | /Optional Param/ "opt_fields" - Defines fields to return. Some requests return *compact* representations of objects in order to conserve resources and complete the request more efficiently. Other times requests return more information than you may need. This option allows you to list the exact set of fields that the API should be sure to return for the objects. The field names should be provided as paths, described below. The id of included objects will always be returned, regardless of the field options.
instance HasOptionalParam CreateProjectForWorkspace OptFields where
  applyOptionalParam req (OptFields xs) =
    req `setQuery` toQueryColl CommaSeparated ("opt_fields", Just xs)

-- | @application/json@
instance Consumes CreateProjectForWorkspace MimeJSON

-- | @application/json@
instance Produces CreateProjectForWorkspace MimeJSON


-- *** deleteProject

-- | @DELETE \/projects\/{project_gid}@
-- 
-- Delete a project
-- 
-- A specific, existing project can be deleted by making a DELETE request on the URL for that project.  Returns an empty data record.
-- 
-- AuthMethod: 'AuthOAuthOauth2', 'AuthBasicPersonalAccessToken'
-- 
deleteProject 
  :: ProjectGid -- ^ "projectGid" -  Globally unique identifier for the project.
  -> AsanaRequest DeleteProject MimeNoContent InlineResponse2001 MimeJSON
deleteProject (ProjectGid projectGid) =
  _mkRequest "DELETE" ["/projects/",toPath projectGid]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthOAuthOauth2)
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicPersonalAccessToken)

data DeleteProject  

-- | /Optional Param/ "opt_pretty" - Provides “pretty” output. Provides the response in a “pretty” format. In the case of JSON this means doing proper line breaking and indentation to make it readable. This will take extra time and increase the response size so it is advisable only to use this during debugging.
instance HasOptionalParam DeleteProject OptPretty where
  applyOptionalParam req (OptPretty xs) =
    req `setQuery` toQuery ("opt_pretty", Just xs)

-- | /Optional Param/ "opt_fields" - Defines fields to return. Some requests return *compact* representations of objects in order to conserve resources and complete the request more efficiently. Other times requests return more information than you may need. This option allows you to list the exact set of fields that the API should be sure to return for the objects. The field names should be provided as paths, described below. The id of included objects will always be returned, regardless of the field options.
instance HasOptionalParam DeleteProject OptFields where
  applyOptionalParam req (OptFields xs) =
    req `setQuery` toQueryColl CommaSeparated ("opt_fields", Just xs)
-- | @application/json@
instance Produces DeleteProject MimeJSON


-- *** duplicateProject

-- | @POST \/projects\/{project_gid}\/duplicate@
-- 
-- Duplicate a project
-- 
-- Creates and returns a job that will asynchronously handle the duplication.
-- 
-- AuthMethod: 'AuthOAuthOauth2', 'AuthBasicPersonalAccessToken'
-- 
duplicateProject 
  :: (Consumes DuplicateProject MimeJSON)
  => ProjectGid -- ^ "projectGid" -  Globally unique identifier for the project.
  -> AsanaRequest DuplicateProject MimeJSON InlineResponse2007 MimeJSON
duplicateProject (ProjectGid projectGid) =
  _mkRequest "POST" ["/projects/",toPath projectGid,"/duplicate"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthOAuthOauth2)
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicPersonalAccessToken)

data DuplicateProject 
instance HasBodyParam DuplicateProject InlineObject18 

-- | /Optional Param/ "opt_pretty" - Provides “pretty” output. Provides the response in a “pretty” format. In the case of JSON this means doing proper line breaking and indentation to make it readable. This will take extra time and increase the response size so it is advisable only to use this during debugging.
instance HasOptionalParam DuplicateProject OptPretty where
  applyOptionalParam req (OptPretty xs) =
    req `setQuery` toQuery ("opt_pretty", Just xs)

-- | /Optional Param/ "opt_fields" - Defines fields to return. Some requests return *compact* representations of objects in order to conserve resources and complete the request more efficiently. Other times requests return more information than you may need. This option allows you to list the exact set of fields that the API should be sure to return for the objects. The field names should be provided as paths, described below. The id of included objects will always be returned, regardless of the field options.
instance HasOptionalParam DuplicateProject OptFields where
  applyOptionalParam req (OptFields xs) =
    req `setQuery` toQueryColl CommaSeparated ("opt_fields", Just xs)

-- | @application/json@
instance Consumes DuplicateProject MimeJSON

-- | @application/json@
instance Produces DuplicateProject MimeJSON


-- *** getProject

-- | @GET \/projects\/{project_gid}@
-- 
-- Get a project
-- 
-- Returns the complete project record for a single project.
-- 
-- AuthMethod: 'AuthOAuthOauth2', 'AuthBasicPersonalAccessToken'
-- 
getProject 
  :: ProjectGid -- ^ "projectGid" -  Globally unique identifier for the project.
  -> AsanaRequest GetProject MimeNoContent InlineResponse2014 MimeJSON
getProject (ProjectGid projectGid) =
  _mkRequest "GET" ["/projects/",toPath projectGid]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthOAuthOauth2)
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicPersonalAccessToken)

data GetProject  

-- | /Optional Param/ "opt_pretty" - Provides “pretty” output. Provides the response in a “pretty” format. In the case of JSON this means doing proper line breaking and indentation to make it readable. This will take extra time and increase the response size so it is advisable only to use this during debugging.
instance HasOptionalParam GetProject OptPretty where
  applyOptionalParam req (OptPretty xs) =
    req `setQuery` toQuery ("opt_pretty", Just xs)

-- | /Optional Param/ "opt_fields" - Defines fields to return. Some requests return *compact* representations of objects in order to conserve resources and complete the request more efficiently. Other times requests return more information than you may need. This option allows you to list the exact set of fields that the API should be sure to return for the objects. The field names should be provided as paths, described below. The id of included objects will always be returned, regardless of the field options.
instance HasOptionalParam GetProject OptFields where
  applyOptionalParam req (OptFields xs) =
    req `setQuery` toQueryColl CommaSeparated ("opt_fields", Just xs)
-- | @application/json@
instance Produces GetProject MimeJSON


-- *** getProjects

-- | @GET \/projects@
-- 
-- Get multiple projects
-- 
-- Returns the compact project records for some filtered set of projects. Use one or more of the parameters provided to filter the projects returned.
-- 
-- AuthMethod: 'AuthOAuthOauth2', 'AuthBasicPersonalAccessToken'
-- 
getProjects 
  :: AsanaRequest GetProjects MimeNoContent InlineResponse20011 MimeJSON
getProjects =
  _mkRequest "GET" ["/projects"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthOAuthOauth2)
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicPersonalAccessToken)

data GetProjects  

-- | /Optional Param/ "opt_pretty" - Provides “pretty” output. Provides the response in a “pretty” format. In the case of JSON this means doing proper line breaking and indentation to make it readable. This will take extra time and increase the response size so it is advisable only to use this during debugging.
instance HasOptionalParam GetProjects OptPretty where
  applyOptionalParam req (OptPretty xs) =
    req `setQuery` toQuery ("opt_pretty", Just xs)

-- | /Optional Param/ "opt_fields" - Defines fields to return. Some requests return *compact* representations of objects in order to conserve resources and complete the request more efficiently. Other times requests return more information than you may need. This option allows you to list the exact set of fields that the API should be sure to return for the objects. The field names should be provided as paths, described below. The id of included objects will always be returned, regardless of the field options.
instance HasOptionalParam GetProjects OptFields where
  applyOptionalParam req (OptFields xs) =
    req `setQuery` toQueryColl CommaSeparated ("opt_fields", Just xs)

-- | /Optional Param/ "limit" - Results per page. The number of objects to return per page. The value must be between 1 and 100.
instance HasOptionalParam GetProjects Limit where
  applyOptionalParam req (Limit xs) =
    req `setQuery` toQuery ("limit", Just xs)

-- | /Optional Param/ "offset" - Offset token. An offset to the next page returned by the API. A pagination request will return an offset token, which can be used as an input parameter to the next request. If an offset is not passed in, the API will return the first page of results. 'Note: You can only pass in an offset that was returned to you via a previously paginated request.'
instance HasOptionalParam GetProjects Offset where
  applyOptionalParam req (Offset xs) =
    req `setQuery` toQuery ("offset", Just xs)

-- | /Optional Param/ "workspace" - The workspace or organization to filter projects on.
instance HasOptionalParam GetProjects Workspace where
  applyOptionalParam req (Workspace xs) =
    req `setQuery` toQuery ("workspace", Just xs)

-- | /Optional Param/ "team" - The team to filter projects on.
instance HasOptionalParam GetProjects Team where
  applyOptionalParam req (Team xs) =
    req `setQuery` toQuery ("team", Just xs)

-- | /Optional Param/ "archived" - Only return projects whose `archived` field takes on the value of this parameter.
instance HasOptionalParam GetProjects Archived where
  applyOptionalParam req (Archived xs) =
    req `setQuery` toQuery ("archived", Just xs)
-- | @application/json@
instance Produces GetProjects MimeJSON


-- *** getProjectsForTask

-- | @GET \/tasks\/{task_gid}\/projects@
-- 
-- Get projects a task is in
-- 
-- Returns a compact representation of all of the projects the task is in.
-- 
-- AuthMethod: 'AuthOAuthOauth2', 'AuthBasicPersonalAccessToken'
-- 
getProjectsForTask 
  :: TaskGid -- ^ "taskGid" -  The task to operate on.
  -> AsanaRequest GetProjectsForTask MimeNoContent InlineResponse20011 MimeJSON
getProjectsForTask (TaskGid taskGid) =
  _mkRequest "GET" ["/tasks/",toPath taskGid,"/projects"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthOAuthOauth2)
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicPersonalAccessToken)

data GetProjectsForTask  

-- | /Optional Param/ "opt_pretty" - Provides “pretty” output. Provides the response in a “pretty” format. In the case of JSON this means doing proper line breaking and indentation to make it readable. This will take extra time and increase the response size so it is advisable only to use this during debugging.
instance HasOptionalParam GetProjectsForTask OptPretty where
  applyOptionalParam req (OptPretty xs) =
    req `setQuery` toQuery ("opt_pretty", Just xs)

-- | /Optional Param/ "opt_fields" - Defines fields to return. Some requests return *compact* representations of objects in order to conserve resources and complete the request more efficiently. Other times requests return more information than you may need. This option allows you to list the exact set of fields that the API should be sure to return for the objects. The field names should be provided as paths, described below. The id of included objects will always be returned, regardless of the field options.
instance HasOptionalParam GetProjectsForTask OptFields where
  applyOptionalParam req (OptFields xs) =
    req `setQuery` toQueryColl CommaSeparated ("opt_fields", Just xs)

-- | /Optional Param/ "limit" - Results per page. The number of objects to return per page. The value must be between 1 and 100.
instance HasOptionalParam GetProjectsForTask Limit where
  applyOptionalParam req (Limit xs) =
    req `setQuery` toQuery ("limit", Just xs)

-- | /Optional Param/ "offset" - Offset token. An offset to the next page returned by the API. A pagination request will return an offset token, which can be used as an input parameter to the next request. If an offset is not passed in, the API will return the first page of results. 'Note: You can only pass in an offset that was returned to you via a previously paginated request.'
instance HasOptionalParam GetProjectsForTask Offset where
  applyOptionalParam req (Offset xs) =
    req `setQuery` toQuery ("offset", Just xs)
-- | @application/json@
instance Produces GetProjectsForTask MimeJSON


-- *** getProjectsForTeam

-- | @GET \/teams\/{team_gid}\/projects@
-- 
-- Get a team's projects
-- 
-- Returns the compact project records for all projects in the team.
-- 
-- AuthMethod: 'AuthOAuthOauth2', 'AuthBasicPersonalAccessToken'
-- 
getProjectsForTeam 
  :: TeamGid -- ^ "teamGid" -  Globally unique identifier for the team.
  -> AsanaRequest GetProjectsForTeam MimeNoContent InlineResponse20011 MimeJSON
getProjectsForTeam (TeamGid teamGid) =
  _mkRequest "GET" ["/teams/",toPath teamGid,"/projects"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthOAuthOauth2)
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicPersonalAccessToken)

data GetProjectsForTeam  

-- | /Optional Param/ "opt_pretty" - Provides “pretty” output. Provides the response in a “pretty” format. In the case of JSON this means doing proper line breaking and indentation to make it readable. This will take extra time and increase the response size so it is advisable only to use this during debugging.
instance HasOptionalParam GetProjectsForTeam OptPretty where
  applyOptionalParam req (OptPretty xs) =
    req `setQuery` toQuery ("opt_pretty", Just xs)

-- | /Optional Param/ "opt_fields" - Defines fields to return. Some requests return *compact* representations of objects in order to conserve resources and complete the request more efficiently. Other times requests return more information than you may need. This option allows you to list the exact set of fields that the API should be sure to return for the objects. The field names should be provided as paths, described below. The id of included objects will always be returned, regardless of the field options.
instance HasOptionalParam GetProjectsForTeam OptFields where
  applyOptionalParam req (OptFields xs) =
    req `setQuery` toQueryColl CommaSeparated ("opt_fields", Just xs)

-- | /Optional Param/ "limit" - Results per page. The number of objects to return per page. The value must be between 1 and 100.
instance HasOptionalParam GetProjectsForTeam Limit where
  applyOptionalParam req (Limit xs) =
    req `setQuery` toQuery ("limit", Just xs)

-- | /Optional Param/ "offset" - Offset token. An offset to the next page returned by the API. A pagination request will return an offset token, which can be used as an input parameter to the next request. If an offset is not passed in, the API will return the first page of results. 'Note: You can only pass in an offset that was returned to you via a previously paginated request.'
instance HasOptionalParam GetProjectsForTeam Offset where
  applyOptionalParam req (Offset xs) =
    req `setQuery` toQuery ("offset", Just xs)

-- | /Optional Param/ "archived" - Only return projects whose `archived` field takes on the value of this parameter.
instance HasOptionalParam GetProjectsForTeam Archived where
  applyOptionalParam req (Archived xs) =
    req `setQuery` toQuery ("archived", Just xs)
-- | @application/json@
instance Produces GetProjectsForTeam MimeJSON


-- *** getProjectsForWorkspace

-- | @GET \/workspaces\/{workspace_gid}\/projects@
-- 
-- Get all projects in a workspace
-- 
-- Returns the compact project records for all projects in the workspace.
-- 
-- AuthMethod: 'AuthOAuthOauth2', 'AuthBasicPersonalAccessToken'
-- 
getProjectsForWorkspace 
  :: WorkspaceGid -- ^ "workspaceGid" -  Globally unique identifier for the workspace or organization.
  -> AsanaRequest GetProjectsForWorkspace MimeNoContent InlineResponse20011 MimeJSON
getProjectsForWorkspace (WorkspaceGid workspaceGid) =
  _mkRequest "GET" ["/workspaces/",toPath workspaceGid,"/projects"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthOAuthOauth2)
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicPersonalAccessToken)

data GetProjectsForWorkspace  

-- | /Optional Param/ "opt_pretty" - Provides “pretty” output. Provides the response in a “pretty” format. In the case of JSON this means doing proper line breaking and indentation to make it readable. This will take extra time and increase the response size so it is advisable only to use this during debugging.
instance HasOptionalParam GetProjectsForWorkspace OptPretty where
  applyOptionalParam req (OptPretty xs) =
    req `setQuery` toQuery ("opt_pretty", Just xs)

-- | /Optional Param/ "opt_fields" - Defines fields to return. Some requests return *compact* representations of objects in order to conserve resources and complete the request more efficiently. Other times requests return more information than you may need. This option allows you to list the exact set of fields that the API should be sure to return for the objects. The field names should be provided as paths, described below. The id of included objects will always be returned, regardless of the field options.
instance HasOptionalParam GetProjectsForWorkspace OptFields where
  applyOptionalParam req (OptFields xs) =
    req `setQuery` toQueryColl CommaSeparated ("opt_fields", Just xs)

-- | /Optional Param/ "limit" - Results per page. The number of objects to return per page. The value must be between 1 and 100.
instance HasOptionalParam GetProjectsForWorkspace Limit where
  applyOptionalParam req (Limit xs) =
    req `setQuery` toQuery ("limit", Just xs)

-- | /Optional Param/ "offset" - Offset token. An offset to the next page returned by the API. A pagination request will return an offset token, which can be used as an input parameter to the next request. If an offset is not passed in, the API will return the first page of results. 'Note: You can only pass in an offset that was returned to you via a previously paginated request.'
instance HasOptionalParam GetProjectsForWorkspace Offset where
  applyOptionalParam req (Offset xs) =
    req `setQuery` toQuery ("offset", Just xs)

-- | /Optional Param/ "archived" - Only return projects whose `archived` field takes on the value of this parameter.
instance HasOptionalParam GetProjectsForWorkspace Archived where
  applyOptionalParam req (Archived xs) =
    req `setQuery` toQuery ("archived", Just xs)
-- | @application/json@
instance Produces GetProjectsForWorkspace MimeJSON


-- *** getTaskCountsForProject

-- | @GET \/projects\/{project_gid}\/task_counts@
-- 
-- Get task count of a project
-- 
-- Get an object that holds task count fields. **All fields are excluded by default**. You must [opt in](#input-output-options) using `opt_fields` to get any information from this endpoint.  This endpoint has an additional [rate limit](#standard-rate-limits) and each field counts especially high against our [cost limits](#cost-limits).  Milestones are just tasks, so they are included in the `num_tasks`, `num_incomplete_tasks`, and `num_completed_tasks` counts.
-- 
-- AuthMethod: 'AuthOAuthOauth2', 'AuthBasicPersonalAccessToken'
-- 
getTaskCountsForProject 
  :: ProjectGid -- ^ "projectGid" -  Globally unique identifier for the project.
  -> AsanaRequest GetTaskCountsForProject MimeNoContent InlineResponse20016 MimeJSON
getTaskCountsForProject (ProjectGid projectGid) =
  _mkRequest "GET" ["/projects/",toPath projectGid,"/task_counts"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthOAuthOauth2)
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicPersonalAccessToken)

data GetTaskCountsForProject  

-- | /Optional Param/ "opt_pretty" - Provides “pretty” output. Provides the response in a “pretty” format. In the case of JSON this means doing proper line breaking and indentation to make it readable. This will take extra time and increase the response size so it is advisable only to use this during debugging.
instance HasOptionalParam GetTaskCountsForProject OptPretty where
  applyOptionalParam req (OptPretty xs) =
    req `setQuery` toQuery ("opt_pretty", Just xs)

-- | /Optional Param/ "opt_fields" - Defines fields to return. Some requests return *compact* representations of objects in order to conserve resources and complete the request more efficiently. Other times requests return more information than you may need. This option allows you to list the exact set of fields that the API should be sure to return for the objects. The field names should be provided as paths, described below. The id of included objects will always be returned, regardless of the field options.
instance HasOptionalParam GetTaskCountsForProject OptFields where
  applyOptionalParam req (OptFields xs) =
    req `setQuery` toQueryColl CommaSeparated ("opt_fields", Just xs)

-- | /Optional Param/ "limit" - Results per page. The number of objects to return per page. The value must be between 1 and 100.
instance HasOptionalParam GetTaskCountsForProject Limit where
  applyOptionalParam req (Limit xs) =
    req `setQuery` toQuery ("limit", Just xs)

-- | /Optional Param/ "offset" - Offset token. An offset to the next page returned by the API. A pagination request will return an offset token, which can be used as an input parameter to the next request. If an offset is not passed in, the API will return the first page of results. 'Note: You can only pass in an offset that was returned to you via a previously paginated request.'
instance HasOptionalParam GetTaskCountsForProject Offset where
  applyOptionalParam req (Offset xs) =
    req `setQuery` toQuery ("offset", Just xs)
-- | @application/json@
instance Produces GetTaskCountsForProject MimeJSON


-- *** removeCustomFieldSettingForProject

-- | @POST \/projects\/{project_gid}\/removeCustomFieldSetting@
-- 
-- Remove a custom field from a project
-- 
-- Removes a custom field setting from a project.
-- 
-- AuthMethod: 'AuthOAuthOauth2', 'AuthBasicPersonalAccessToken'
-- 
removeCustomFieldSettingForProject 
  :: (Consumes RemoveCustomFieldSettingForProject MimeJSON, MimeRender MimeJSON InlineObject22)
  => InlineObject22 -- ^ "inlineObject22"
  -> ProjectGid -- ^ "projectGid" -  Globally unique identifier for the project.
  -> AsanaRequest RemoveCustomFieldSettingForProject MimeJSON InlineResponse2001 MimeJSON
removeCustomFieldSettingForProject inlineObject22 (ProjectGid projectGid) =
  _mkRequest "POST" ["/projects/",toPath projectGid,"/removeCustomFieldSetting"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthOAuthOauth2)
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicPersonalAccessToken)
    `setBodyParam` inlineObject22

data RemoveCustomFieldSettingForProject 
instance HasBodyParam RemoveCustomFieldSettingForProject InlineObject22 

-- | /Optional Param/ "opt_pretty" - Provides “pretty” output. Provides the response in a “pretty” format. In the case of JSON this means doing proper line breaking and indentation to make it readable. This will take extra time and increase the response size so it is advisable only to use this during debugging.
instance HasOptionalParam RemoveCustomFieldSettingForProject OptPretty where
  applyOptionalParam req (OptPretty xs) =
    req `setQuery` toQuery ("opt_pretty", Just xs)

-- | @application/json@
instance Consumes RemoveCustomFieldSettingForProject MimeJSON

-- | @application/json@
instance Produces RemoveCustomFieldSettingForProject MimeJSON


-- *** removeFollowersForProject

-- | @POST \/projects\/{project_gid}\/removeFollowers@
-- 
-- Remove followers from a project
-- 
-- Removes the specified list of users from following the project, this will not affect project membership status. Returns the updated project record.
-- 
-- AuthMethod: 'AuthOAuthOauth2', 'AuthBasicPersonalAccessToken'
-- 
removeFollowersForProject 
  :: (Consumes RemoveFollowersForProject MimeJSON, MimeRender MimeJSON InlineObject26)
  => InlineObject26 -- ^ "inlineObject26"
  -> ProjectGid -- ^ "projectGid" -  Globally unique identifier for the project.
  -> AsanaRequest RemoveFollowersForProject MimeJSON InlineResponse2001 MimeJSON
removeFollowersForProject inlineObject26 (ProjectGid projectGid) =
  _mkRequest "POST" ["/projects/",toPath projectGid,"/removeFollowers"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthOAuthOauth2)
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicPersonalAccessToken)
    `setBodyParam` inlineObject26

data RemoveFollowersForProject 
instance HasBodyParam RemoveFollowersForProject InlineObject26 

-- | /Optional Param/ "opt_pretty" - Provides “pretty” output. Provides the response in a “pretty” format. In the case of JSON this means doing proper line breaking and indentation to make it readable. This will take extra time and increase the response size so it is advisable only to use this during debugging.
instance HasOptionalParam RemoveFollowersForProject OptPretty where
  applyOptionalParam req (OptPretty xs) =
    req `setQuery` toQuery ("opt_pretty", Just xs)

-- | /Optional Param/ "opt_fields" - Defines fields to return. Some requests return *compact* representations of objects in order to conserve resources and complete the request more efficiently. Other times requests return more information than you may need. This option allows you to list the exact set of fields that the API should be sure to return for the objects. The field names should be provided as paths, described below. The id of included objects will always be returned, regardless of the field options.
instance HasOptionalParam RemoveFollowersForProject OptFields where
  applyOptionalParam req (OptFields xs) =
    req `setQuery` toQueryColl CommaSeparated ("opt_fields", Just xs)

-- | @application/json@
instance Consumes RemoveFollowersForProject MimeJSON

-- | @application/json@
instance Produces RemoveFollowersForProject MimeJSON


-- *** removeMembersForProject

-- | @POST \/projects\/{project_gid}\/removeMembers@
-- 
-- Remove users from a project
-- 
-- Removes the specified list of users from members of the project. Returns the updated project record.
-- 
-- AuthMethod: 'AuthOAuthOauth2', 'AuthBasicPersonalAccessToken'
-- 
removeMembersForProject 
  :: (Consumes RemoveMembersForProject MimeJSON, MimeRender MimeJSON InlineObject24)
  => InlineObject24 -- ^ "inlineObject24"
  -> ProjectGid -- ^ "projectGid" -  Globally unique identifier for the project.
  -> AsanaRequest RemoveMembersForProject MimeJSON InlineResponse2001 MimeJSON
removeMembersForProject inlineObject24 (ProjectGid projectGid) =
  _mkRequest "POST" ["/projects/",toPath projectGid,"/removeMembers"]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthOAuthOauth2)
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicPersonalAccessToken)
    `setBodyParam` inlineObject24

data RemoveMembersForProject 
instance HasBodyParam RemoveMembersForProject InlineObject24 

-- | /Optional Param/ "opt_pretty" - Provides “pretty” output. Provides the response in a “pretty” format. In the case of JSON this means doing proper line breaking and indentation to make it readable. This will take extra time and increase the response size so it is advisable only to use this during debugging.
instance HasOptionalParam RemoveMembersForProject OptPretty where
  applyOptionalParam req (OptPretty xs) =
    req `setQuery` toQuery ("opt_pretty", Just xs)

-- | /Optional Param/ "opt_fields" - Defines fields to return. Some requests return *compact* representations of objects in order to conserve resources and complete the request more efficiently. Other times requests return more information than you may need. This option allows you to list the exact set of fields that the API should be sure to return for the objects. The field names should be provided as paths, described below. The id of included objects will always be returned, regardless of the field options.
instance HasOptionalParam RemoveMembersForProject OptFields where
  applyOptionalParam req (OptFields xs) =
    req `setQuery` toQueryColl CommaSeparated ("opt_fields", Just xs)

-- | @application/json@
instance Consumes RemoveMembersForProject MimeJSON

-- | @application/json@
instance Produces RemoveMembersForProject MimeJSON


-- *** updateProject

-- | @PUT \/projects\/{project_gid}@
-- 
-- Update a project
-- 
-- A specific, existing project can be updated by making a PUT request on the URL for that project. Only the fields provided in the `data` block will be updated; any unspecified fields will remain unchanged.  When using this method, it is best to specify only those fields you wish to change, or else you may overwrite changes made by another user since you last retrieved the task.  Returns the complete updated project record.
-- 
-- AuthMethod: 'AuthOAuthOauth2', 'AuthBasicPersonalAccessToken'
-- 
updateProject 
  :: (Consumes UpdateProject MimeJSON, MimeRender MimeJSON InlineObject17)
  => InlineObject17 -- ^ "inlineObject17"
  -> ProjectGid -- ^ "projectGid" -  Globally unique identifier for the project.
  -> AsanaRequest UpdateProject MimeJSON InlineResponse2014 MimeJSON
updateProject inlineObject17 (ProjectGid projectGid) =
  _mkRequest "PUT" ["/projects/",toPath projectGid]
    `_hasAuthType` (P.Proxy :: P.Proxy AuthOAuthOauth2)
    `_hasAuthType` (P.Proxy :: P.Proxy AuthBasicPersonalAccessToken)
    `setBodyParam` inlineObject17

data UpdateProject 
instance HasBodyParam UpdateProject InlineObject17 

-- | /Optional Param/ "opt_pretty" - Provides “pretty” output. Provides the response in a “pretty” format. In the case of JSON this means doing proper line breaking and indentation to make it readable. This will take extra time and increase the response size so it is advisable only to use this during debugging.
instance HasOptionalParam UpdateProject OptPretty where
  applyOptionalParam req (OptPretty xs) =
    req `setQuery` toQuery ("opt_pretty", Just xs)

-- | /Optional Param/ "opt_fields" - Defines fields to return. Some requests return *compact* representations of objects in order to conserve resources and complete the request more efficiently. Other times requests return more information than you may need. This option allows you to list the exact set of fields that the API should be sure to return for the objects. The field names should be provided as paths, described below. The id of included objects will always be returned, regardless of the field options.
instance HasOptionalParam UpdateProject OptFields where
  applyOptionalParam req (OptFields xs) =
    req `setQuery` toQueryColl CommaSeparated ("opt_fields", Just xs)

-- | @application/json@
instance Consumes UpdateProject MimeJSON

-- | @application/json@
instance Produces UpdateProject MimeJSON

